### ISSUE TITLE
Scheduling ignores initial time parameter

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-jobs#2]
When setting schedules of the form 'R/T09:00:00Z/P1D', the time portion 'T09:00:00Z' is ignored and the job is scheduled immediately. 

After the job runs, the job.schedule field is then updated such that the run time of the job replaces the 'T09:00:00Z' portion. This creates two problems: 1) the initial start period is lost forever, and 2) time drift may become a problem for long-running sites due to the scheduler's idle period (default being 30 seconds). This could cause the job to drift into the future 1-2 hours a year.

**Comment by msporny** [comment]
Potential fixes:

* Save the initial schedule time (if it doesn't include a date?) to prevent time drift.
* Re-calculate next run time based on initial schedule time instead of last run time.

**Comment by dlongley** [comment]
The existing code (at least in part) supports a different (valid) use case. So it looks like we have two different use cases now:

1. Run a job N time units after the last job completed (current implementation).
2. Run a job every N time units regardless of job completion time (new request).

We should make sure that the second use case makes sense and, if so, add support for it without disrupting the existing use case support.

**Comment by dlongley** [comment]
We should consider making the scheduler's idle period depend on the next job to run (instead of or as an alternative to the default idle time).

**Comment by mattcollier** [comment]
Does not apply to v3, closing.
