### ISSUE TITLE
Automatically determine `scheduler.idleTime`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-jobs#3]
We should explore automatically and dynamically handling `scheduler.idleTime` instead of using an explicitly configured value every time (that is hard for people to understand how it ought to be set).

On start up, the job scheduler should run. Upon completion, it should check to see when the next earliest job may need to run and schedule itself to run then unless that would be longer than the `scheduler.idleTime`. That way a configured `scheduler.idleTime` will really only mean "the maximum time to wait" and that time would really only ever be used on jobless databases.

**Comment by mattcollier** [comment]
Does not apply to v3, closing.
